Repository hmrc/trusts-frontend, pull requests merged in 2019-06, with the labels that each got.

#164 [TRUS-1199] - Declaration
  app/mapping/DeclarationMapper.scala
  test/mapping/DeclarationMapperSpec.scala
Labels: Ready For Review

#166 [TRUS-1031] - Registration Progress - Summary text
  app/controllers/DeclarationController.scala
  app/controllers/TaskListController.scala
  app/pages/RegistrationProgress.scala
  app/views/TaskListView.scala.html
  conf/messages.en
  test/controllers/TaskListControllerSpec.scala
  test/pages/RegistrationProgressSpec.scala
  test/views/TaskListViewSpec.scala
Labels: Ready For Review

#169 Removing tax liability link from task list and showing beta banner and feedback link.
  app/config/FrontendAppConfig.scala
  app/controllers/TaskListController.scala
  app/views/GovukWrapper.scala.html
  app/views/MainTemplate.scala.html
  conf/application.conf
  test/base/SpecBase.scala
  test/controllers/TaskListControllerSpec.scala
Labels: Accepted

#173 [TRUS-755] | saving submission date in db.
  app/controllers/DeclarationController.scala
  app/pages/RegistrationSubmissionDatePage.scala
Labels: Accepted

#175 TRUS-755 Confirmation page for new and existing trusts
  app/controllers/ConfirmationController.scala
  app/models/entities/LeadTrusteeIndividual.scala
  app/models/entities/Trustee.scala
  app/models/entities/TrusteeIndividual.scala
  app/views/ConfirmationView.scala.html
  app/views/components/link.scala.html
  conf/messages.en
  test/controllers/ConfirmationControllerSpec.scala
  test/views/ConfirmationViewSpec.scala
  test/views/ViewSpecBase.scala
Labels: Accepted

#174 [TRUS-754] Declaration warning for organisation user.
  app/controllers/DeclarationController.scala
  app/views/DeclarationView.scala.html
  conf/messages.en
  test/controllers/DeclarationControllerSpec.scala
  test/views/DeclarationViewSpec.scala
Labels: Ready For Review

#179 Adding toggle for whitelist enabled or not
  app/config/FrontendAppConfig.scala
  app/filters/WhitelistFilter.scala
  conf/application.conf
Labels: Accepted

#185 reading config value as string.
  app/config/FrontendAppConfig.scala
Labels: Accepted

#189 [TRUS-1262] Updated shares section information on interrupt page.
  conf/messages.en
Labels: Accepted

#186 [TRUS-729] - Contents, error messages and date component markup amended
  app/views/WhenTrustSetupView.scala.html
  app/views/components/input_date.scala.html
  conf/app.routes
  conf/messages.en
Labels: Accepted, Ready to Merge

#192 correcting change mode for couple of links.
  app/navigation/Navigator.scala
  test/navigation/navigators/TrustDetailsRoutes.scala
Labels: Ready For Review

#191 [TRUS-1034] - New pattern for Client Reference Number
  app/assets/stylesheets/trustsfrontend-app.scss
  app/forms/Validation.scala
  app/views/AgentInternalReferenceView.scala.html
  app/views/components/input_text.scala.html
  conf/messages.en
Labels: Ready For Review, Ready to Merge
