Repository hmrc/trusts-frontend, pull requests merged in 2019-11, with the labels that each got.

#351 Trust IV locked and Trust status page
  app/controllers/TrustStatusController.scala
  app/controllers/WhatIsTheUTRVariationsController.scala
  app/navigation/VariationsNavigator.scala
  app/views/playback/status/ClosedErrorView.scala.html
  app/views/playback/status/DoesNotMatchErrorView.scala.html
  app/views/playback/status/IVDownView.scala.html
  app/views/playback/status/StillProcessingErrorView.scala.html
  app/views/playback/status/TrustLockedView.scala.html
  conf/messages.en
  test/controllers/TrustStatusControllerSpec.scala
  test/filters/SessionIdFilterSpec.scala
  test/views/TrustLockedViewSpec.scala
Labels: Accepted

#350 [TRUS-1975] - Correct navigation for saved registrations
  app/controllers/AgentOverviewController.scala
  app/views/TaskListView.scala.html
  app/views/components/draft_registration_list_row.scala.html
  conf/app.routes
  conf/application.conf
  test/controllers/AgentOverviewControllerSpec.scala
  test/views/TaskListViewSpec.scala
Labels: Accepted

#354 TRUS-1541
  app/controllers/UTRSentByPostController.scala
  app/views/UTRSentByPostView.scala.html
  conf/messages.en
  test/controllers/UTRSentByPostControllerSpec.scala
  test/views/UTRSentByPostViewSpec.scala
Labels: Comments Added

#361 TRUS-1501
  app/views/AssetMoneyValueView.scala.html
  app/views/components/input_text.scala.html
  app/views/property_or_land/PropertyLandValueTrustView.scala.html
  app/views/property_or_land/PropertyOrLandTotalValueView.scala.html
  app/views/shares/SharePortfolioValueInTrustView.scala.html
  app/views/shares/ShareValueInTrustView.scala.html
Labels: Accepted

#367 [TRUS-1384] - PR Amends
  app/assets/stylesheets/trustsfrontend-app.scss
  app/config/FrontendAppConfig.scala
  app/controllers/playback/DeclarationController.scala
  app/forms/playback/DeclarationFormProvider.scala
  app/models/playback/Declaration.scala
  app/navigation/VariationsNavigator.scala
  app/pages/playback/DeclarationPage.scala
  app/views/playback/DeclarationView.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages.en
  test/controllers/DeclarationWhatNextControllerSpec.scala
  test/controllers/playback/DeclarationControllerSpec.scala
  test/forms/playback/DeclarationFormProviderSpec.scala
  test/generators/ModelGenerators.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/navigation/VariationsNavigatorSpec.scala
  test/pages/playback/DeclarationPageSpec.scala
  test/views/playback/DeclarationViewSpec.scala
Labels: Accepted

#371 [TRUS-2010] - Toggle off email reference in Declaration pages for MVP
  app/config/FrontendAppConfig.scala
  app/controllers/playback/DeclarationController.scala
  app/forms/DeclarationFormProvider.scala
  app/forms/playback/DeclarationFormProvider.scala
  app/mapping/registration/DeclarationMapper.scala
  app/models/core/pages/Declaration.scala
  app/models/playback/pages/Declaration.scala
  app/pages/DeclarationPage.scala
  app/pages/playback/DeclarationPage.scala
  app/views/DeclarationView.scala.html
  app/views/playback/DeclarationView.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages.en
  test/controllers/DeclarationControllerSpec.scala
  test/controllers/playback/DeclarationControllerSpec.scala
  test/forms/DeclarationFormProviderSpec.scala
  test/forms/playback/DeclarationFormProviderSpec.scala
  test/generators/ModelGenerators.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/mapping/DeclarationMapperSpec.scala
  test/pages/DeclarationPageSpec.scala
  test/utils/TestUserAnswers.scala
  test/views/DeclarationViewSpec.scala
  test/views/playback/DeclarationViewSpec.scala
Labels: Ready For Review

#375 TRUS-2039 Charity extractor, setting value to DiscretionYesNo when no share of income provided
  app/mapping/playback/CharityBeneficiaryExtractor.scala
  test/mapping/playback/CharityBeneficiaryExtractorSpec.scala
Labels: Accepted
