Repository hmrc/trusts-frontend, pull requests merged in 2019-05, with the labels that each got.

#108 individual-ben-accessibility
  app/views/IndividualBeneficiaryDateOfBirthYesNoView.scala.html
  app/views/IndividualBeneficiaryNationalInsuranceNumberView.scala.html
  app/views/IndividualBeneficiaryNationalInsuranceYesNoView.scala.html
  app/views/IndividualBeneficiaryVulnerableYesNoView.scala.html
  conf/messages.en
Labels: Ready For Review

#110 Beneficiary messages
  conf/messages.en
Labels: Accepted

#113 Individual ben uk address
  app/controllers/IndividualBeneficiaryAddressUKController.scala
  app/controllers/IndividualBeneficiaryAnswersController.scala
  app/navigation/Navigator.scala
  app/pages/IndividualBeneficiaryAddressUKPage.scala
  app/pages/IndividualBeneficiaryAddressYesNoPage.scala
  app/utils/CheckYourAnswersHelper.scala
  app/views/IndividualBeneficiaryAddressUKView.scala.html
  conf/app.routes
  conf/messages.en
  test/controllers/IndividualBeneficiaryAddressUKControllerSpec.scala
  test/forms/IndividualBeneficiaryAddressUKFormProviderSpec.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/navigation/navigators/BeneficiaryRoutes.scala
  test/pages/IndividualBeneficiaryAddressUKPageSpec.scala
  test/views/IndividualBeneficiaryAddressUKViewSpec.scala
Labels: Ready For Review

#115 nino yes no clean up logic
  app/navigation/TaskListNavigator.scala
  app/pages/IndividualBeneficiaryNationalInsuranceYesNoPage.scala
  test/pages/IndividualBeneficiaryNationalInsuranceYesNoPageSpec.scala
Labels: Accepted

#116 Add beneficiary
  app/controllers/AddABeneficiaryController.scala
  app/models/AddABeneficiary.scala
  app/models/entities/IndividualBeneficiary.scala
  app/navigation/Navigator.scala
  app/navigation/TaskListNavigator.scala
  app/utils/AddABeneficiaryViewHelper.scala
  app/utils/CheckYourAnswersHelper.scala
  app/views/AddABeneficiaryView.scala.html
  app/views/IndividualBeneficiaryIncomeYesNoView.scala.html
  conf/app.routes
  conf/messages.en
  test/controllers/AddABeneficiaryControllerSpec.scala
  test/forms/AgentTelephoneNumberFormProviderSpec.scala
  test/navigation/TaskListNavigatorSpec.scala
  test/navigation/navigators/BeneficiaryRoutes.scala
  test/views/AddABeneficiaryViewSpec.scala
  test/views/IndividualBeneficiaryIncomeYesNoViewSpec.scala
Labels: Ready For Review

#119 delete not required objects.
  app/controllers/IndividualBeneficiaryAddressUKController.scala
  app/forms/IndividualBeneficiaryAddressUKFormProvider.scala
  app/models/IndividualBeneficiaryAddressUK.scala
  app/pages/IndividualBeneficiaryAddressUKPage.scala
  test/controllers/IndividualBeneficiaryAddressUKControllerSpec.scala
  test/generators/ModelGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/pages/IndividualBeneficiaryAddressUKPageSpec.scala
  test/views/IndividualBeneficiaryAddressUKViewSpec.scala
Labels: Accepted

#120 updated to remove not used objects for name.
  app/forms/IndividualBeneficiaryNameFormProvider.scala
  app/models/IndividualBeneficiaryName.scala
  app/pages/IndividualBeneficiaryNamePage.scala
  test/controllers/IndividualBeneficiaryNameControllerSpec.scala
  test/generators/ModelGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
Labels: Accepted

#124 Update to use domain nino validation
  app/forms/IndividualBeneficiaryNationalInsuranceNumberFormProvider.scala
  app/forms/Validation.scala
  app/forms/mappings/Constraints.scala
  project/AppDependencies.scala
  test/forms/IndividualBeneficiaryNationalInsuranceNumberFormProviderSpec.scala
  test/forms/behaviours/StringFieldBehaviours.scala
Labels: Accepted

#126 nino validation for trustee and settlor.
  app/forms/SettlorNationalInsuranceNumberFormProvider.scala
  app/forms/TrusteesNinoFormProvider.scala
  test/forms/SettlorNationalInsuranceNumberFormProviderSpec.scala
  test/forms/TrusteesNinoFormProviderSpec.scala
Labels: Accepted

#127 changes to not populate add beneficiary value.
  app/controllers/AddABeneficiaryController.scala
  test/controllers/AddABeneficiaryControllerSpec.scala
Labels: Accepted

#129 nino formatting on check your answer page.
  app/utils/CheckYourAnswersHelper.scala
  test/controllers/DeceasedSettlorAnswerControllerSpec.scala
  test/controllers/IndividualBeneficiaryAnswersControllerSpec.scala
  test/controllers/TrusteesAnswerPageControllerSpec.scala
Labels: Ready For Review

#131 [TRUS-1002] Clean up logic for trustee pages.
  app/navigation/Navigator.scala
  app/pages/IsThisLeadTrusteePage.scala
  app/pages/TrusteeIndividualOrBusinessPage.scala
  app/pages/TrusteeLiveInTheUKPage.scala
  test/controllers/AddATrusteeControllerSpec.scala
  test/controllers/TelephoneNumberControllerSpec.scala
  test/controllers/TrusteeAUKCitizenControllerSpec.scala
  test/controllers/TrusteeLiveInTheUKControllerSpec.scala
  test/controllers/TrusteesNinoControllerSpec.scala
  test/navigation/navigators/TrusteeRoutes.scala
  test/pages/IsThisLeadTrusteePageSpec.scala
  test/pages/TrusteeIndividualOrBusinessPageSpec.scala
  test/pages/TrusteeLiveInTheUKPageSpec.scala
  test/utils/AddATrusteeViewHelperSpec.scala
Labels: Accepted

#132 changed text middle name to middle names.
  conf/messages.en
Labels: Accepted

#128 TRUS-474
  app/navigation/Navigator.scala
  conf/messages.en
  test/controllers/AgentNameControllerSpec.scala
  test/models/MongoDateTimeFormatsSpec.scala
  test/navigation/navigators/AgentRoutes.scala
Labels: Accepted

#135 TRUS-1048
  app/controllers/AgentAnswerController.scala
  app/controllers/AgentUKAddressController.scala
  app/navigation/Navigator.scala
  app/pages/AgentUKAddressPage.scala
  app/utils/CheckYourAnswersHelper.scala
  app/views/AgentUKAddressView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/AgentUKAddress.sh
  test/controllers/AgentAnswerControllerSpec.scala
  test/controllers/AgentUKAddressControllerSpec.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/navigation/navigators/AgentRoutes.scala
  test/pages/AgentUKAddressPageSpec.scala
  test/views/AgentUKAddressViewSpec.scala
Labels: Accepted

#134 Fix country lookup
  app/assets/javascripts/trustsfrontend.js
  app/views/SettlorsInternationalAddressView.scala.html
  app/views/TrustPreviouslyResidentView.scala.html
Labels: Ready For Review

#136 [TRUS-973] - Add to Asset Interrupt Page
  app/navigation/TaskListNavigator.scala
  app/views/AssetInterruptPageView.scala.html
  conf/messages.en
  test/navigation/TaskListNavigatorSpec.scala
  test/views/AssetInterruptPageViewSpec.scala
Labels: Accepted

#137 [TRUS-392] Class of beneficiary description page.
  app/controllers/ClassBeneficiaryDescriptionController.scala
  app/forms/ClassBeneficiaryDescriptionFormProvider.scala
  app/forms/Validation.scala
  app/models/entities/ClassOfBeneficiary.scala
  app/pages/ClassBeneficiaryDescriptionPage.scala
  app/pages/ClassOfBeneficiaries.scala
  app/utils/CheckYourAnswersHelper.scala
  app/views/ClassBeneficiaryDescriptionView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/ClassBeneficiaryDescription.sh
  test/controllers/ClassBeneficiaryDescriptionControllerSpec.scala
  test/forms/ClassBeneficiaryDescriptionFormProviderSpec.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/pages/ClassBeneficiaryDescriptionPageSpec.scala
  test/views/ClassBeneficiaryDescriptionViewSpec.scala
Labels: Accepted

#140 updated invalid description error message.
  conf/messages.en
Labels: Accepted

#141 [TRUS-342] Selecting type of beneficiary page
  app/controllers/WhatTypeOfBeneficiaryController.scala
  app/forms/WhatTypeOfBeneficiaryFormProvider.scala
  app/models/WhatTypeOfBeneficiary.scala
  app/navigation/Navigator.scala
  app/pages/WhatTypeOfBeneficiaryPage.scala
  app/views/WhatTypeOfBeneficiaryView.scala.html
  app/views/components/input_radio.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/WhatTypeOfBeneficiary.sh
  test/controllers/WhatTypeOfBeneficiaryControllerSpec.scala
  test/forms/WhatTypeOfBeneficiaryFormProviderSpec.scala
  test/generators/ModelGenerators.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/models/WhatTypeOfBeneficiarySpec.scala
  test/navigation/navigators/BeneficiaryRoutes.scala
  test/pages/WhatTypeOfBeneficiaryPageSpec.scala
  test/views/WhatTypeOfBeneficiaryViewSpec.scala
Labels: Accepted

#145 TRUS-1052: Error message update
  conf/messages.en
Labels: Accepted

#143 [TRUS-1031] - Registration Progress - Summary text
  app/controllers/TaskListController.scala
  app/models/entities/Trustee.scala
  app/pages/RegistrationProgress.scala
  app/views/TaskListView.scala.html
  conf/messages.en
  test/controllers/AddATrusteeControllerSpec.scala
  test/controllers/TaskListControllerSpec.scala
  test/models/reads/TrusteeReadsSpec.scala
  test/utils/AddATrusteeViewHelperSpec.scala
  test/views/TaskListViewSpec.scala
Labels: Ready For Review

#146 TRUS-755 | Confirmation Page
  app/assets/stylesheets/trustsfrontend-app.scss
  app/config/FrontendAppConfig.scala
  app/controllers/ConfirmationController.scala
  app/views/ConfirmationView.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages.en
  migrations/applied_migrations/Confirmation.sh
  test/controllers/ConfirmationControllerSpec.scala
  test/views/ConfirmationViewSpec.scala
Labels: Comments Added

#144 [TRUS-321] Linking beneficiaries pages.
  app/navigation/Navigator.scala
  app/navigation/TaskListNavigator.scala
  app/utils/AddABeneficiaryViewHelper.scala
  app/views/IndividualBeneficiaryInfoView.scala.html
  app/views/components/button_link.scala.html
  test/controllers/AddABeneficiaryControllerSpec.scala
  test/navigation/TaskListNavigatorSpec.scala
  test/navigation/navigators/BeneficiaryRoutes.scala
  test/views/AddABeneficiaryViewSpec.scala
  test/views/IndividualBeneficiaryInfoViewSpec.scala
  test/views/ViewSpecBase.scala
  test/views/behaviours/ViewBehaviours.scala
Labels: Accepted

#152 [TUST-1192] Mapping trustee type
  app/mapping/NameMapper.scala
  app/mapping/TrusteeMapper.scala
  test/mapping/TrusteeMapperSpec.scala
Labels: Accepted

#153 Deceased Settlor Mapping
  app/mapping/DeceasedSettlorMapper.scala
  test/mapping/DeceasedSettlorMapperSpec.scala
Labels: Ready For Review

#157 [TRUS-1196] Mapping of lead trustee
  app/mapping/AddressMapper.scala
  app/mapping/LeadTrusteeMapper.scala
  app/mapping/SchemaModels.scala
  app/mapping/TrusteeMapper.scala
  app/models/entities/LeadTrusteeIndividual.scala
  app/models/entities/Trustee.scala
  app/models/entities/TrusteeIndividual.scala
  test/mapping/LeadTrusteeMapperSpec.scala
  test/mapping/TrusteeMapperSpec.scala
  test/models/reads/TrusteeReadsSpec.scala
Labels: Accepted

#155 TRUS-1193 Tax Liability mapper
  app/mapping/NameMapper.scala
  app/mapping/SchemaModels.scala
  app/mapping/TaxLiabilityMapper.scala
  test/mapping/DeceasedSettlorMapperSpec.scala
  test/mapping/TaxLiabilityMapperSpec.scala
Labels: Accepted
