Repository hmrc/trusts-frontend, pull requests merged in 2019-03, with the labels that each got.

#38 Trus 585 - Does the trustee live in the uk
  app/controllers/TrusteeLiveInTheUKController.scala
  app/controllers/TrusteesAnswerPageController.scala
  app/forms/TrusteeLiveInTheUKFormProvider.scala
  app/pages/TrusteeLiveInTheUKPage.scala
  app/utils/CheckYourAnswersHelper.scala
  app/views/TrusteeLiveInTheUKView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/TrusteeLiveInTheUK.sh
  test/controllers/TrusteeIndividualOrBusinessControllerSpec.scala
  test/controllers/TrusteeLiveInTheUKControllerSpec.scala
  test/controllers/TrusteesAnswerPageControllerSpec.scala
  test/forms/TrusteeLiveInTheUKFormProviderSpec.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/pages/TrusteeLiveInTheUKPageSpec.scala
  test/views/TrusteeLiveInTheUKViewSpec.scala
Labels: Comments Added

#39 Fix navigation between trutees page and content
  app/navigation/Navigator.scala
  app/pages/TrusteeLiveInTheUKPage.scala
  conf/messages.en
  test/navigation/navigators/TrusteeRoutes.scala
Labels: Accepted

#43 [TRUS-588] - Correct Telephone RegEx
  app/forms/Validation.scala
Labels: Ready For Review

#44 [TRUS-482] - Interrupt page
  app/assets/stylesheets/trustsfrontend-app.scss
  app/controllers/TrusteesInfoController.scala
  app/views/TrusteesInfoView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/TrusteesInfo.sh
  test/controllers/TrusteesInfoControllerSpec.scala
  test/views/TrusteesInfoViewSpec.scala
Labels: Accepted

#42 [TRUS-472] - Agent overview - Register a trust for a client - No saved registrations
  app/config/Module.scala
  app/controllers/AgentOverviewController.scala
  app/controllers/IndexController.scala
  app/controllers/actions/IdentifierAction.scala
  app/controllers/actions/RequiredAffinityGroupAction.scala
  app/models/requests/IdentifierRequest.scala
  app/views/AgentOverviewView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/AgentOverview.sh
  test/base/SpecBase.scala
  test/controllers/AgentOverviewControllerSpec.scala
  test/controllers/IndexControllerSpec.scala
  test/controllers/actions/DataRetrievalActionSpec.scala
  test/controllers/actions/FakeIdentifierAction.scala
  test/controllers/actions/RequiredAffinityGroupActionSpec.scala
  test/views/AgentOverviewViewSpec.scala
Labels: Ready For Review

#51 Rename logback file in test
  test/resources/logback-test.xml
Labels: Ready For Review

#52 [TRUS-906] - Accessibility - Jaws & VO - H1 repeated as part of hint text
  app/assets/javascripts/trustsfrontend.js
  app/assets/stylesheets/trustsfrontend-app.scss
  app/views/TrustHaveAUTRView.scala.html
  app/views/TrustRegisteredOnlineView.scala.html
  app/views/TrusteesNameView.scala.html
  app/views/WhatIsTheUTRView.scala.html
  app/views/components/error_summary.scala.html
  app/views/components/input_text.scala.html
  app/views/components/input_yes_no.scala.html
  conf/messages.en
  test/views/ViewSpecBase.scala
  test/views/behaviours/QuestionViewBehaviours.scala
  test/views/behaviours/YesNoViewBehaviours.scala
Labels: Accepted

#54 [TRUS-906] - Accessibility - Jaws & VO - H1 repeated as part of hint text
  app/assets/stylesheets/trustsfrontend-app.scss
  app/views/PostcodeForTheTrustView.scala.html
  app/views/TrustNameView.scala.html
  app/views/WhatIsTheUTRView.scala.html
  app/views/components/back_link.scala.html
  app/views/components/form_hint.scala.html
  app/views/components/input_text.scala.html
  app/views/components/input_yes_no.scala.html
  conf/messages.en
Labels: Accepted

#55 [TRUS-907] - Accessibility - Jaws - 'dash' announced
  conf/messages.en
Labels: Accepted

#48 TRUS-477 | Created agentanswers page, added test and sections to view
  app/controllers/AgentAnswerController.scala
  app/navigation/Navigator.scala
  app/views/AgentAnswerView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/AgentAnswer.sh
  test/controllers/AgentAnswerControllerSpec.scala
  test/navigation/NavigatorSpec.scala
  test/navigation/navigators/AgentRoutes.scala
  test/views/AgentAnswerViewSpec.scala
Labels: Accepted, Ready to Merge

#57 [TRUS-904] - Accessibility - Jaws - Back link does not work
  app/assets/javascripts/trustsfrontend.js
Labels: Accepted

#53 Trus 811- Created AssetInteruptPage | Added tests and CSS to fix padding
  app/controllers/AssetInterruptPageController.scala
  app/views/AssetInterruptPageView.scala.html
  app/views/TrusteesInfoView.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/AssetInterruptPage.sh
  test/controllers/AssetInterruptPageControllerSpec.scala
  test/views/AssetInterruptPageViewSpec.scala
Labels: Accepted

#58 [TRUS-820] - CBT - Country selection field too long when activated
  app/assets/stylesheets/trustsfrontend-app.scss
Labels: Accepted

#59 TRUS-820 Fix for responsive country lookup
  app/assets/stylesheets/trustsfrontend-app.scss
Labels: Accepted

#62 [TRUS-930] - Accessibility - Country List
  app/assets/javascripts/autocomplete/location-autocomplete.min.js
  app/assets/javascripts/autocomplete/location-autocomplete.min.js.map
  app/assets/javascripts/trustsfrontend.js
  app/forms/CountryGoverningTrustFormProvider.scala
  app/views/CountryAdministeringTrustView.scala.html
  app/views/CountryGoverningTrustView.scala.html
  app/views/components/input_yes_no.scala.html
  app/views/components/select.scala.html
  app/views/components/submit_button.scala.html
Labels: Accepted

#63 [TRUS-910] - Accessibility - NVDA & VO - UTR
  app/views/TrustHaveAUTRView.scala.html
  app/views/components/form_hint.scala.html
  app/views/components/input_yes_no.scala.html
  conf/messages.en
Labels: Accepted

#64 [TRUS-930] - Accessibility - Country List
  app/assets/javascripts/trustsfrontend.js
Labels: Accepted
